export const mockData = [
  { name: "已垫", count: 2, gacha_type: "400" },
  { name: "希格雯", count: 23, gacha_type: "400" },
  { name: "玛薇卡", count: 75, gacha_type: "301" },
  { name: "茜特菈莉", count: 68, gacha_type: "400" },
  { name: "恰斯卡", count: 78, gacha_type: "301" },
  { name: "七七", count: 78, gacha_type: "301" },
  { name: "希诺宁", count: 64, gacha_type: "301" },
  { name: "基尼奇", count: 78, gacha_type: "301" },
  { name: "玛拉妮", count: 71, gacha_type: "301" },
  { name: "艾梅莉埃", count: 80, gacha_type: "301" },
  { name: "莫娜", count: 83, gacha_type: "301" },
  { name: "克洛琳德", count: 77, gacha_type: "301" },
  { name: "提纳里", count: 40, gacha_type: "400" },
  { name: "阿蕾奇诺", count: 45, gacha_type: "301" },
  { name: "七七", count: 29, gacha_type: "301" },
  { name: "已垫", count: 6, gacha_type: "302" },
  { name: "已垫", count: 9, gacha_type: "200" },
  { name: "天空之翼", count: 79, gacha_type: "200" },
  { name: "七七", count: 40, gacha_type: "200" },
];

export const mockData2 = [
  { name: "已垫", count: 10, gacha_type: "301" },
  { name: "杜林", count: 24, gacha_type: "301" },
  { name: "提纳里", count: 21, gacha_type: "301" },
  { name: "奈芙尔", count: 81, gacha_type: "301" },
  { name: "菲林斯", count: 27, gacha_type: "301" },
  { name: "梦见月瑞希", count: 11, gacha_type: "301" },
  { name: "菈乌玛", count: 15, gacha_type: "301" },
  { name: "莫娜", count: 76, gacha_type: "301" },
  { name: "伊涅芙", count: 78, gacha_type: "301" },
  { name: "丝柯克", count: 78, gacha_type: "301" },
  { name: "迪卢克", count: 81, gacha_type: "301" },
  { name: "爱可菲", count: 83, gacha_type: "301" },
  { name: "迪卢克", count: 78, gacha_type: "301" },
  { name: "瓦雷莎", count: 17, gacha_type: "301" },
  { name: "迪卢克", count: 82, gacha_type: "301" },
  { name: "希格雯", count: 18, gacha_type: "400" },
  { name: "已垫", count: 61, gacha_type: "200" },
  { name: "七七", count: 81, gacha_type: "200" },
  { name: "四风原典", count: 16, gacha_type: "200" },
  { name: "天空之翼", count: 17, gacha_type: "200" },
];
